#!/bin/bash

_sudo=`which sudo`
if [ -z $_sudo ]
then
    echo "sudo is not fonud"
    exit 1
fi

passwd=$1
pwdfile="$HOME/.monitor_windows.pwd"

if [ -z $passwd ]
then
    if [ -f $pwdfile ]
    then
        passwd=`cat $pwdfile`
        echo $passwd|$_sudo -S ./netmonitor.py &#> /dev/null &
        echo
    else
        echo "please entry User password for sudo"
        echo "exp: $0 password"
        echo "if put wrong password, you can find $HOME/.monitor_windows.pwd file and to edit password"
        exit 1
    fi
else
    echo $passwd > $pwdfile
    echo $passwd|$_sudo -S ./netmonitor.py &#> /dev/null &
    echo
fi
